-- Migration: Créer la table whatsapp_subscribers
-- Date: 2026-06-02
-- Description: Crée la table whatsapp_subscribers pour gérer le consentement (opt-in/opt-out).

CREATE TABLE IF NOT EXISTS whatsapp_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(32) UNIQUE NOT NULL,
    name VARCHAR(255) NULL,
    status VARCHAR(20) DEFAULT 'active' NOT NULL CHECK (status IN ('active', 'inactive')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ajouter un commentaire pour documenter la table
COMMENT ON TABLE whatsapp_subscribers IS 'Table stockant les abonnés WhatsApp et leur statut de consentement (opt-in/opt-out)';

-- Index pour accélérer la recherche par numéro de téléphone
CREATE INDEX IF NOT EXISTS idx_whatsapp_subscribers_phone ON whatsapp_subscribers(phone);

-- Trigger pour mettre à jour automatiquement updated_at
CREATE OR REPLACE FUNCTION update_whatsapp_subscribers_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_update_whatsapp_subscribers_updated_at
    BEFORE UPDATE ON whatsapp_subscribers
    FOR EACH ROW
    EXECUTE FUNCTION update_whatsapp_subscribers_updated_at();

-- Vérification
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 
        FROM information_schema.tables 
        WHERE table_name = 'whatsapp_subscribers'
    ) THEN
        RAISE NOTICE 'Migration réussie: La table whatsapp_subscribers a été créée';
    ELSE
        RAISE NOTICE 'Migration en cours d''application: La table whatsapp_subscribers sera créée lors de l''exécution SQL';
    END IF;
END $$;
