-- Migration: Créer la table push_subscriptions
-- Date: 2026-09-24
-- Description: Stocke les abonnements aux notifications push web (VAPID) des vendeurs.

CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendeur_id BIGINT NOT NULL REFERENCES vendeurs(id) ON DELETE CASCADE,
    endpoint TEXT UNIQUE NOT NULL,
    p256dh VARCHAR(255) NOT NULL,
    auth VARCHAR(255) NOT NULL,
    user_agent TEXT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ajouter un commentaire pour documenter la table
COMMENT ON TABLE push_subscriptions IS 'Abonnements Web Push (VAPID) des vendeurs, un par navigateur/appareil';

-- Index pour accélérer la recherche des abonnements d'un vendeur
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_vendeur_id ON push_subscriptions(vendeur_id);

-- Trigger pour mettre à jour automatiquement updated_at
CREATE OR REPLACE FUNCTION update_push_subscriptions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_update_push_subscriptions_updated_at
    BEFORE UPDATE ON push_subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION update_push_subscriptions_updated_at();

-- Vérification
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_name = 'push_subscriptions'
    ) THEN
        RAISE NOTICE 'Migration réussie: La table push_subscriptions a été créée';
    ELSE
        RAISE NOTICE 'Migration en cours d''application: La table push_subscriptions sera créée lors de l''exécution SQL';
    END IF;
END $$;
