-- Migration: Clés d'accès vendeur (WebAuthn)
-- Date: 2026-09-25
-- Description: Stocke les clés publiques et les défis à usage unique.

CREATE TABLE IF NOT EXISTS vendeur_passkeys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendeur_id BIGINT NOT NULL REFERENCES vendeurs(id) ON DELETE CASCADE,
    credential_id TEXT NOT NULL UNIQUE,
    public_key BYTEA NOT NULL,
    counter BIGINT NOT NULL DEFAULT 0,
    device_name VARCHAR(255) NULL,
    transports TEXT[] NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_vendeur_passkeys_vendeur_id ON vendeur_passkeys(vendeur_id);

COMMENT ON TABLE vendeur_passkeys IS 'Clés publiques WebAuthn des vendeurs. Aucune donnée biométrique.';

CREATE TABLE IF NOT EXISTS vendeur_passkey_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendeur_id BIGINT NULL REFERENCES vendeurs(id) ON DELETE CASCADE,
    challenge TEXT NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('register', 'login')),
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_vendeur_passkey_challenges_challenge ON vendeur_passkey_challenges(challenge);
CREATE INDEX IF NOT EXISTS idx_vendeur_passkey_challenges_expires ON vendeur_passkey_challenges(expires_at);

CREATE OR REPLACE FUNCTION update_vendeur_passkeys_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_update_vendeur_passkeys_updated_at
    BEFORE UPDATE ON vendeur_passkeys
    FOR EACH ROW
    EXECUTE FUNCTION update_vendeur_passkeys_updated_at();
