-- Migration: Créer la table billets (événements)
-- Date: 2026-09-23
-- Description: Numéros séquentiels par produit événement, jeton public par commande.

CREATE TABLE IF NOT EXISTS billets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id INTEGER NOT NULL REFERENCES commandes(id) ON DELETE CASCADE,
    produit_id INTEGER NOT NULL REFERENCES produits(id) ON DELETE RESTRICT,
    type_billet VARCHAR(255) NOT NULL,
    numero INTEGER NOT NULL,
    jeton VARCHAR(64) NOT NULL,
    date_creation TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT billets_produit_numero_unique UNIQUE (produit_id, numero)
);

CREATE INDEX IF NOT EXISTS idx_billets_commande_id ON billets(commande_id);
CREATE INDEX IF NOT EXISTS idx_billets_jeton ON billets(jeton);
CREATE INDEX IF NOT EXISTS idx_billets_produit_id ON billets(produit_id);

COMMENT ON TABLE billets IS 'Billets événement : numéro séquentiel par produit, jeton de consultation par commande';

ALTER TABLE commandes ADD COLUMN IF NOT EXISTS client_email VARCHAR(255);
